### ISSUE TITLE
Configure GoReleaser environment

### ISSUE THREAD

**Issue by danielpacak** [goharbor/harbor-scanner-clair#5]
The project uses GoReleaser to publish compiled binaries to GitHub release page as well as pushing the Docker image to Docker Hub. Such publishing job is triggered whenever you create an annotated Git tag.

https://github.com/goharbor/harbor-scanner-clair/blob/master/.travis.yml#L30

To keep using GoReleaser,  the following environment variables must to be set in Travis.

| Environment Variable | Description |
|----------------------|-------------|
| `GITHUB_TOKEN`       | GitHub API token with the `repo` scope to deploy the artifacts to GitHub |
| `DOCKERHUB_USER`     | DockerHub username |
| `DOCKERHUB_TOKEN`    | DockerHub access token to push images |

**Comment by steven-zou** [comment]
Code checked in, see PR https://github.com/goharbor/harbor-scanner-clair/pull/6
